// Auto-generated by build.js — do not edit directly.
// All-in-one Cloudflare Worker for drag-and-drop upload to Cloudflare Pages.
// For the structured Pages Functions deployment, use functions/api/ instead.


    async function handleFetchDeck(request, url) {
        const corsHeaders = {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
            'Content-Type': 'application/json'
        };
        if (request.method === 'OPTIONS') {
            return new Response(null, { status: 204, headers: corsHeaders });
        }
        const deckUrl = url.searchParams.get('url');
        if (!deckUrl) {
            return new Response(JSON.stringify({ error: "Missing URL parameter" }), { status: 400, headers: corsHeaders });
        }
        try {
            let deckListText = "", deckName = "";
            if (deckUrl.includes("moxfield.com")) {
                const match = deckUrl.match(/moxfield\.com\/decks\/([a-zA-Z0-9\-_]+)/);
                if (!match) throw new Error("Invalid Moxfield URL format");
                const apiUrl = `https://api.moxfield.com/v2/decks/all/${match[1]}`;
                const response = await fetch(apiUrl, {
                    headers: {
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Referer': 'https://www.moxfield.com/', 'Accept': 'application/json'
                    }
                });
                if (!response.ok) throw new Error(`Moxfield API error: ${response.status}`);
                const data = await response.json();
                deckName = data.name;
                const moxCmdrs = data.commanders ? Object.keys(data.commanders) : [];
                if (moxCmdrs.length > 0) {
                    deckListText += "Commander\n";
                    Object.entries(data.commanders).forEach(([k, v]) => { deckListText += `${v.quantity} ${k}\n`; });
                    deckListText += "\n";
                }
                if (data.mainboard) Object.entries(data.mainboard).forEach(([k, v]) => { deckListText += `${v.quantity} ${k}\n`; });
            } else if (deckUrl.includes("archidekt.com")) {
                const match = deckUrl.match(/archidekt\.com\/decks\/(\d+)/);
                if (!match) throw new Error("Invalid Archidekt URL format");
                const apiUrl = `https://archidekt.com/api/decks/${match[1]}/`;
                const response = await fetch(apiUrl, {
                    headers: {
                        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
                        'Referer': 'https://archidekt.com/', 'Accept': 'application/json'
                    }
                });
                if (!response.ok) throw new Error(`Archidekt API error: ${response.status}`);
                const data = await response.json();
                deckName = data.name;
                if (data.cards) {
                    const cmdrs  = data.cards.filter(c => c.categories?.includes('Commander'));
                    const others = data.cards.filter(c => !c.categories?.includes('Commander') && !["Sideboard","Maybeboard"].includes(c.categories?.[0]));
                    if (cmdrs.length > 0) {
                        deckListText += "Commander\n";
                        cmdrs.forEach(c => { deckListText += `${c.quantity} ${c.card.oracleCard.name}\n`; });
                        deckListText += "\n";
                    }
                    others.forEach(c => { deckListText += `${c.quantity} ${c.card.oracleCard.name}\n`; });
                }
            } else {
                return new Response(JSON.stringify({ error: "Unsupported site. Currently supports Moxfield and Archidekt." }), { status: 400, headers: corsHeaders });
            }
            const cmdrSectionMatch = deckListText.match(/Commander\n([\s\S]+?)\n\n/);
            const commanders = [];
            if (cmdrSectionMatch) {
                for (const line of cmdrSectionMatch[1].trim().split('\n')) {
                    const name = line.replace(/^\d+[xX]?\s+/, '').replace(/\s*\([A-Za-z0-9]{2,6}\)\s*\d*/g, '').split(' // ')[0].trim();
                    if (name) commanders.push(name);
                }
            }
            const commander = commanders.length > 0 ? commanders.join(' & ') : null;
            return new Response(JSON.stringify({ name: deckName, list: deckListText, commander }), { status: 200, headers: corsHeaders });
        } catch (error) {
            return new Response(JSON.stringify({ error: error.message }), { status: 500, headers: corsHeaders });
        }
    }



    async function handleRankings(request, url, env) {
        const corsHeaders = {
            'Access-Control-Allow-Origin': '*',
            'Access-Control-Allow-Methods': 'GET, OPTIONS',
            'Access-Control-Allow-Headers': 'Content-Type',
            'Content-Type': 'application/json'
        };
        if (request.method === 'OPTIONS') {
            return new Response(null, { status: 204, headers: corsHeaders });
        }
        const commanderName = url.searchParams.get('commander');
        if (!commanderName || !commanderName.trim()) {
            return new Response(JSON.stringify({ error: 'Missing commander parameter' }), { status: 400, headers: corsHeaders });
        }
        if (!env.EDHREC_RANKINGS) {
            return new Response(JSON.stringify({ error: 'EDHREC_RANKINGS KV namespace is not bound.' }), { status: 503, headers: corsHeaders });
        }
        try {
            const nameLower = commanderName.trim().toLowerCase();
            const tfs = ['pastweek', 'pastmonth', 'past2years'];
            const results = {};
            for (const tf of tfs) {
                const raw = await env.EDHREC_RANKINGS.get(tf);
                if (!raw) { results[tf] = 'Not cached yet'; continue; }
                const list = JSON.parse(raw);
                const idx  = list.findIndex(c => c.name.toLowerCase() === nameLower);
                results[tf] = idx >= 0 ? idx + 1 : 'Unranked';
            }
            const cachedAt = await env.EDHREC_RANKINGS.get('lastUpdated');
            return new Response(JSON.stringify({
                commander: commanderName.trim(),
                pastweek: results.pastweek, pastmonth: results.pastmonth, past2years: results.past2years,
                cachedAt: cachedAt || null
            }), { status: 200, headers: corsHeaders });
        } catch (error) {
            return new Response(JSON.stringify({ error: error.message }), { status: 500, headers: corsHeaders });
        }
    }


export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === '/api/fetch-deck') return handleFetchDeck(request, url);
    if (url.pathname === '/api/rankings')   return handleRankings(request, url, env);

    // Serve static assets via Cloudflare Pages ASSETS binding
    return env.ASSETS.fetch(request);
  }
};
